### ISSUE TITLE
Duplicating Lines of Text Bug

### ISSUE THREAD

**Issue by Mmoniot1** [AtomLinter/linter-luacheck#40] opened 2017-12-20 21:10 UTC
I have been having trouble with lines of text duplicating as I am editing a lua file. The text is not a part of the file, and will disappear if the line it is on is edited. This regularly is a problem for me in atom, and I have recently narrowed down the cause to the luacheck package by systematically disabling all of my other community packages.

Here is a demonstration of the bug on an arbitrary lua script, with no extraneous community packages enabled:

![bug](https://user-images.githubusercontent.com/34722269/34227549-67b474aa-e582-11e7-9cbf-f7812ed3fa46.gif)

As you can see, the lines on which collapsed code appear are the only ones to duplicate. They do not duplicate on their own, but only occasionally when the script is scrolled through or edited. The duplicate text disappears if the line it appears on is edited, scrolled off screen or uncollapsed. Using the command in atom to collapse everything strangely also dismisses all duplicate text, despite the lines it appears on always being lines where the code is already collapsed.
I can repeat this bug in nearly all lua scripts on my machine, and I have detected no pattern as to what lines will duplicate beyond where ever any code is collapsed. There are some lines where this always happens, and some where this never happens, these lines will stay consistent in their behavior even if I restart atom, and only change if the file is edited significantly.
I am running the latest version of atom 1.23.1 on Windows 10. I have gone through many updates to luacheck and its dependencies, and have not seen this glitch clear up. language-lua, linter, linter-luacheck, and linter-ui-default should be the most up to date version, their version number can be seen in the report gif. The glitch occurs it seems even if  I change theme, reset my config or reinstall atom. I do not have another machine to test if I can reproduce the bug on it.

**Comment by Positive07** [comment] 2017-12-21 19:49
This bug cannot be caused by linter-luacheck itself, since the plugin does not perform any modification on the text at all. It could be caused by other packages, like linter-ui-default itself.

Have you tried disabling linter-luacheck and see if the error persists?

**Comment by Mmoniot1** [comment] 2017-12-24 22:25
sorry, yes. Replacing the linter-ui-default package with a different ui package eliminates the issue.

**Comment by Positive07** [comment] 2017-12-24 23:20
Alright, I'll close it here, but you can report it over there and link to this issue.

Thanks for your feedback, if you have any other issue please feel free to report them!
Have a nice holiday

**Closed by Positive07** 2017-12-24 23:20 UTC
